Repository cefsharp/CefSharp, pull requests merged in 2018-12, with the labels that each got.

#2590 WinForms - Added missing Browsable attribute on JavascriptObjectRepository + Updated DefaultValue attribute on UseParentFormMessageInterceptor
  CefSharp.WinForms/ChromiumWebBrowser.cs
Labels: winforms

#2589 WPF - Change PixelFormat from Bgra32 to Pbgra32 to fix control transparency
  CefSharp.Wpf.Example/Controls/ChromiumWebBrowserWithScreenshotSupport.cs
  CefSharp.Wpf/Rendering/Experimental/ByteArrayWritableBitmapRenderHandler.cs
  CefSharp.Wpf/Rendering/Experimental/IncreaseBufferInteropRenderHandler.cs
  CefSharp.Wpf/Rendering/InteropBitmapRenderHandler.cs
  CefSharp.Wpf/Rendering/WritableBitmapRenderHandler.cs
Labels: wpf

#2597 Refactoring - Move CefCookie conversion to TypeConversion
  CefSharp.Core/Internals/ClientAdapter.cpp
  CefSharp.Core/Internals/CookieVisitor.cpp
  CefSharp.Core/Internals/TypeConversion.h
  CefSharp.Core/ResourceHandlerWrapper.cpp
Labels: code-cleanup

#2605 Cef.Get* - Added initialize checks to Cef.Get* methods
  CefSharp.Core/Cef.h
Labels: enhancement

#2613 Add Chromium Extension Support
  CefSharp.Core/BrowserSettings.h
  CefSharp.Core/CefSharp.Core.vcxproj
  CefSharp.Core/CefSharp.Core.vcxproj.filters
  CefSharp.Core/Internals/CefBrowserHostWrapper.cpp
  CefSharp.Core/Internals/CefBrowserHostWrapper.h
  CefSharp.Core/Internals/CefExtensionHandlerAdapter.h
  CefSharp.Core/Internals/CefExtensionWrapper.cpp
  CefSharp.Core/Internals/CefExtensionWrapper.h
  CefSharp.Core/Internals/CefGetExtensionResourceCallbackWrapper.h
  CefSharp.Core/ManagedCefBrowserAdapter.h
  CefSharp.Core/RequestContext.h
  CefSharp.Example/CefSharp.Example.csproj
  CefSharp.Example/Extensions/set_page_color/icon.png
  CefSharp.Example/Extensions/set_page_color/manifest.json
  CefSharp.Example/Extensions/set_page_color/popup.html
  CefSharp.Example/Extensions/set_page_color/popup.js
  CefSharp.Example/Handlers/ExtensionHandler.cs
  CefSharp.WinForms.Example/BrowserForm.Designer.cs
  CefSharp.WinForms.Example/BrowserForm.cs
  CefSharp.WinForms/ChromiumWebBrowser.cs
  CefSharp/Callback/IGetExtensionResourceCallback.cs
  CefSharp/CefSharp.csproj
  CefSharp/Handler/IExtensionHandler.cs
  CefSharp/IBrowserHost.cs
  CefSharp/IExtension.cs
  CefSharp/IRequestContext.cs
  CefSharp/RequestContextExtensions.cs
Labels: enhancement
